services:
  minecraft:
    image: itzg/minecraft-server:java17
    container_name: minecraft_halloween_luigi
    tty: "true"
    stdin_open: "true"
    environment:
      EULA: "true"
      VERSION: "1.20.1"
      TYPE: "FORGE"
      FORGEVERSION: "47.3.0"
      MEMORY: "4G"
      ENABLE_ROLLING_LOGS: "true"
      TZ: "Europe/Paris"
      EXEC_DIRECTLY: "true"
      OVERRIDE_SERVER_PROPERTIES: "true"
      SERVER_NAME: "^^ Minecraft Croissy ^^"
      MOTD: "Halloween *** Luigi's Mansion ***"
      MODE: "survival"
      DIFFICULTY: "easy"
      MAX_PLAYERS: 10
      ENABLE_RCON: "true"
      RCON_PASSWORD: minecraft123
      RCON_PORT: "25575"
      WORLD: /tmp/Luigis_Mansion_v1.0.zip
      OPS: "wyst82"
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - ./mods:/mods:ro
      - data:/data
      - ./Luigis_Mansion_v1.0.zip:/tmp/Luigis_Mansion_v1.0.zip
    restart: unless-stopped
volumes:
  data:
