services:
  minecraft:
    build: .
    container_name: minecraft-boiledone
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      TYPE: "FORGE"
      FORGEVERSION: "47.3.0"
      ENABLE_RCON: "true"
      RCON_PASSWORD: minecraft123
      RCON_PORT: "25575"
    volumes:
      - ./data:/data/
    restart: unless-stopped
