services:
  minecraft:
    image: itzg/minecraft-server:java17
    container_name: minecraft_server
    tty: true
    stdin_open: true
    environment:
      EULA: "true"
      VERSION: "1.20.1"
      TYPE: "FORGE"
      FORGEVERSION: "47.3.0"
      MEMORY: "4G"
      ENABLE_ROLLING_LOGS: "true"
      TZ: "Europe/Paris"
      EXEC_DIRECTLY: "true"
      OVERRIDE_SERVER_PROPERTIES: "true"
      SERVER_NAME: "^^ Minecraft Croissy ^^"
      MOTD: "The Boiled One."
      MODE: "creative"
      DIFFICULTY: "easy"
      MAX_PLAYERS: 10
      ENABLE_RCON: "true"
      RCON_PASSWORD: minecraft123
      RCON_PORT: "25575"
      OPS: "wyst82"
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - ./mods:/mods:ro
      - data:/data
    restart: unless-stopped
volumes:
  data:
